package com.bohai.subAccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CapitalRateDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE_DETAIL.USER_NAME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE_DETAIL.USER_CAPITAL_RATE
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    private BigDecimal userCapitalRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE_DETAIL.USER_CAPITAL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    private BigDecimal userCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE_DETAIL.HOST_CAPITAL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    private BigDecimal hostCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE_DETAIL.INSERT_TIME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    private String insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE_DETAIL.USER_NAME
     *
     * @return the value of T_CAPITAL_RATE_DETAIL.USER_NAME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE_DETAIL.USER_NAME
     *
     * @param userName the value for T_CAPITAL_RATE_DETAIL.USER_NAME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE_DETAIL.USER_CAPITAL_RATE
     *
     * @return the value of T_CAPITAL_RATE_DETAIL.USER_CAPITAL_RATE
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public BigDecimal getUserCapitalRate() {
        return userCapitalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE_DETAIL.USER_CAPITAL_RATE
     *
     * @param userCapitalRate the value for T_CAPITAL_RATE_DETAIL.USER_CAPITAL_RATE
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public void setUserCapitalRate(BigDecimal userCapitalRate) {
        this.userCapitalRate = userCapitalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE_DETAIL.USER_CAPITAL
     *
     * @return the value of T_CAPITAL_RATE_DETAIL.USER_CAPITAL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public BigDecimal getUserCapital() {
        return userCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE_DETAIL.USER_CAPITAL
     *
     * @param userCapital the value for T_CAPITAL_RATE_DETAIL.USER_CAPITAL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public void setUserCapital(BigDecimal userCapital) {
        this.userCapital = userCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE_DETAIL.HOST_CAPITAL
     *
     * @return the value of T_CAPITAL_RATE_DETAIL.HOST_CAPITAL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public BigDecimal getHostCapital() {
        return hostCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE_DETAIL.HOST_CAPITAL
     *
     * @param hostCapital the value for T_CAPITAL_RATE_DETAIL.HOST_CAPITAL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public void setHostCapital(BigDecimal hostCapital) {
        this.hostCapital = hostCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE_DETAIL.INSERT_TIME
     *
     * @return the value of T_CAPITAL_RATE_DETAIL.INSERT_TIME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public String getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE_DETAIL.INSERT_TIME
     *
     * @param insertTime the value for T_CAPITAL_RATE_DETAIL.INSERT_TIME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime;
    }
}