package com.bohai.subAccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CapitalRateDetail2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE_DETAIL.USER_NAME
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    private BigDecimal inoutmoney;

	public BigDecimal getInoutmoney() {
		return inoutmoney;
	}

	public void setInoutmoney(BigDecimal inoutmoney) {
		this.inoutmoney = inoutmoney;
	}

  
}