package com.bohai.subAccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GroupRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.GROUP_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.FORCE_CLOSE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal forceCloseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.OPEN_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.CLOSE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GROUP_RULE.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.ID
     *
     * @return the value of T_GROUP_RULE.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.ID
     *
     * @param id the value for T_GROUP_RULE.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.GROUP_ID
     *
     * @return the value of T_GROUP_RULE.GROUP_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.GROUP_ID
     *
     * @param groupId the value for T_GROUP_RULE.GROUP_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.ACCOUNT
     *
     * @return the value of T_GROUP_RULE.ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.ACCOUNT
     *
     * @param account the value for T_GROUP_RULE.ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.FORCE_CLOSE_RATE
     *
     * @return the value of T_GROUP_RULE.FORCE_CLOSE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getForceCloseRate() {
        return forceCloseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.FORCE_CLOSE_RATE
     *
     * @param forceCloseRate the value for T_GROUP_RULE.FORCE_CLOSE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setForceCloseRate(BigDecimal forceCloseRate) {
        this.forceCloseRate = forceCloseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.OPEN_TIME
     *
     * @return the value of T_GROUP_RULE.OPEN_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.OPEN_TIME
     *
     * @param openTime the value for T_GROUP_RULE.OPEN_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.CLOSE_TIME
     *
     * @return the value of T_GROUP_RULE.CLOSE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.CLOSE_TIME
     *
     * @param closeTime the value for T_GROUP_RULE.CLOSE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCloseTime(String closeTime) {
        this.closeTime = closeTime == null ? null : closeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.CREATE_TIME
     *
     * @return the value of T_GROUP_RULE.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.CREATE_TIME
     *
     * @param createTime the value for T_GROUP_RULE.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GROUP_RULE.UPDATE_TIME
     *
     * @return the value of T_GROUP_RULE.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GROUP_RULE.UPDATE_TIME
     *
     * @param updateTime the value for T_GROUP_RULE.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}