package com.bohai.subAccount.entity;

import java.math.BigDecimal;

public class InvestorPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String instrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.BROKERID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String brokerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.INVESTORID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String investorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.POSIDIRECTION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String posidirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.HEDGEFLAG
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String hedgeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.POSITIONDATE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String positiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.YDPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long ydposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.POSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.LONGFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long longfrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SHORTFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long shortfrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.LONGFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal longfrozenamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SHORTFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal shortfrozenamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long openvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CLOSEVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long closevolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal openamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CLOSEAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal closeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.POSITIONCOST
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal positioncost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.PREMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal premargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.USEMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal usemargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.FROZENMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal frozenmargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.FROZENCASH
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal frozencash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.FROZENCOMMISSION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal frozencommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CASHIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal cashin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.COMMISSION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CLOSEPROFIT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal closeprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.POSITIONPROFIT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal positionprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.PRESETTLEMENTPRICE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal presettlementprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SETTLEMENTPRICE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal settlementprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.TRADINGDAY
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String tradingday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SETTLEMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long settlementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENCOST
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal opencost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.EXCHANGEMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal exchangemargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.COMBPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long combposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.COMBLONGFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long comblongfrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.COMBSHORTFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long combshortfrozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CLOSEPROFITBYDATE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal closeprofitbydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CLOSEPROFITBYTRADE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal closeprofitbytrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.TODAYPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private Long todayposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.MARGINRATEBYMONEY
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal marginratebymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.MARGINRATEBYVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal marginratebyvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SUBUSERID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String subuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.FRONTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal frontid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SESSIONID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.ORDERREF
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String orderref;
    
    private String opentime;
    
    private String closetime;
    
    /**
     * 持仓盈亏
     */
    private BigDecimal positionWin;
    
    /**
     * 最新价
     * @return
     */
    private BigDecimal lastPrice;
    
    /**
     * 买一价
     */
    private BigDecimal bidPrice1;
    
    /**
     * 卖一价
     */
    private BigDecimal askPrice1;
    
    /**
     * 涨停价
     */
    private BigDecimal upperLimitPrice;
    
    /**
     * 跌停价 
     */
    private BigDecimal lowerLimitPrice;

    public String getOpentime() {
		return opentime;
	}

	public void setOpentime(String opentime) {
		this.opentime = opentime;
	}

	public String getClosetime() {
		return closetime;
	}

	public void setClosetime(String closetime) {
		this.closetime = closetime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @return the value of T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getInstrumentid() {
        return instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @param instrumentid the value for T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setInstrumentid(String instrumentid) {
        this.instrumentid = instrumentid == null ? null : instrumentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.BROKERID
     *
     * @return the value of T_INVESTOR_POSITION.BROKERID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getBrokerid() {
        return brokerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.BROKERID
     *
     * @param brokerid the value for T_INVESTOR_POSITION.BROKERID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setBrokerid(String brokerid) {
        this.brokerid = brokerid == null ? null : brokerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.INVESTORID
     *
     * @return the value of T_INVESTOR_POSITION.INVESTORID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getInvestorid() {
        return investorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.INVESTORID
     *
     * @param investorid the value for T_INVESTOR_POSITION.INVESTORID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setInvestorid(String investorid) {
        this.investorid = investorid == null ? null : investorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.POSIDIRECTION
     *
     * @return the value of T_INVESTOR_POSITION.POSIDIRECTION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getPosidirection() {
        return posidirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.POSIDIRECTION
     *
     * @param posidirection the value for T_INVESTOR_POSITION.POSIDIRECTION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPosidirection(String posidirection) {
        this.posidirection = posidirection == null ? null : posidirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.HEDGEFLAG
     *
     * @return the value of T_INVESTOR_POSITION.HEDGEFLAG
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getHedgeflag() {
        return hedgeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.HEDGEFLAG
     *
     * @param hedgeflag the value for T_INVESTOR_POSITION.HEDGEFLAG
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setHedgeflag(String hedgeflag) {
        this.hedgeflag = hedgeflag == null ? null : hedgeflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.POSITIONDATE
     *
     * @return the value of T_INVESTOR_POSITION.POSITIONDATE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getPositiondate() {
        return positiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.POSITIONDATE
     *
     * @param positiondate the value for T_INVESTOR_POSITION.POSITIONDATE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPositiondate(String positiondate) {
        this.positiondate = positiondate == null ? null : positiondate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.YDPOSITION
     *
     * @return the value of T_INVESTOR_POSITION.YDPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getYdposition() {
        return ydposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.YDPOSITION
     *
     * @param ydposition the value for T_INVESTOR_POSITION.YDPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setYdposition(Long ydposition) {
        this.ydposition = ydposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.POSITION
     *
     * @return the value of T_INVESTOR_POSITION.POSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.POSITION
     *
     * @param position the value for T_INVESTOR_POSITION.POSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPosition(Long position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.LONGFROZEN
     *
     * @return the value of T_INVESTOR_POSITION.LONGFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getLongfrozen() {
        return longfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.LONGFROZEN
     *
     * @param longfrozen the value for T_INVESTOR_POSITION.LONGFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setLongfrozen(Long longfrozen) {
        this.longfrozen = longfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.SHORTFROZEN
     *
     * @return the value of T_INVESTOR_POSITION.SHORTFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getShortfrozen() {
        return shortfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.SHORTFROZEN
     *
     * @param shortfrozen the value for T_INVESTOR_POSITION.SHORTFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setShortfrozen(Long shortfrozen) {
        this.shortfrozen = shortfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.LONGFROZENAMOUNT
     *
     * @return the value of T_INVESTOR_POSITION.LONGFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getLongfrozenamount() {
        return longfrozenamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.LONGFROZENAMOUNT
     *
     * @param longfrozenamount the value for T_INVESTOR_POSITION.LONGFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setLongfrozenamount(BigDecimal longfrozenamount) {
        this.longfrozenamount = longfrozenamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.SHORTFROZENAMOUNT
     *
     * @return the value of T_INVESTOR_POSITION.SHORTFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getShortfrozenamount() {
        return shortfrozenamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.SHORTFROZENAMOUNT
     *
     * @param shortfrozenamount the value for T_INVESTOR_POSITION.SHORTFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setShortfrozenamount(BigDecimal shortfrozenamount) {
        this.shortfrozenamount = shortfrozenamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.OPENVOLUME
     *
     * @return the value of T_INVESTOR_POSITION.OPENVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getOpenvolume() {
        return openvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.OPENVOLUME
     *
     * @param openvolume the value for T_INVESTOR_POSITION.OPENVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setOpenvolume(Long openvolume) {
        this.openvolume = openvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.CLOSEVOLUME
     *
     * @return the value of T_INVESTOR_POSITION.CLOSEVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getClosevolume() {
        return closevolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.CLOSEVOLUME
     *
     * @param closevolume the value for T_INVESTOR_POSITION.CLOSEVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setClosevolume(Long closevolume) {
        this.closevolume = closevolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @return the value of T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getOpenamount() {
        return openamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @param openamount the value for T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setOpenamount(BigDecimal openamount) {
        this.openamount = openamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.CLOSEAMOUNT
     *
     * @return the value of T_INVESTOR_POSITION.CLOSEAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getCloseamount() {
        return closeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.CLOSEAMOUNT
     *
     * @param closeamount the value for T_INVESTOR_POSITION.CLOSEAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCloseamount(BigDecimal closeamount) {
        this.closeamount = closeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.POSITIONCOST
     *
     * @return the value of T_INVESTOR_POSITION.POSITIONCOST
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getPositioncost() {
        return positioncost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.POSITIONCOST
     *
     * @param positioncost the value for T_INVESTOR_POSITION.POSITIONCOST
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPositioncost(BigDecimal positioncost) {
        this.positioncost = positioncost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.PREMARGIN
     *
     * @return the value of T_INVESTOR_POSITION.PREMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getPremargin() {
        return premargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.PREMARGIN
     *
     * @param premargin the value for T_INVESTOR_POSITION.PREMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPremargin(BigDecimal premargin) {
        this.premargin = premargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.USEMARGIN
     *
     * @return the value of T_INVESTOR_POSITION.USEMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getUsemargin() {
        return usemargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.USEMARGIN
     *
     * @param usemargin the value for T_INVESTOR_POSITION.USEMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setUsemargin(BigDecimal usemargin) {
        this.usemargin = usemargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.FROZENMARGIN
     *
     * @return the value of T_INVESTOR_POSITION.FROZENMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getFrozenmargin() {
        return frozenmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.FROZENMARGIN
     *
     * @param frozenmargin the value for T_INVESTOR_POSITION.FROZENMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setFrozenmargin(BigDecimal frozenmargin) {
        this.frozenmargin = frozenmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.FROZENCASH
     *
     * @return the value of T_INVESTOR_POSITION.FROZENCASH
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getFrozencash() {
        return frozencash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.FROZENCASH
     *
     * @param frozencash the value for T_INVESTOR_POSITION.FROZENCASH
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setFrozencash(BigDecimal frozencash) {
        this.frozencash = frozencash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.FROZENCOMMISSION
     *
     * @return the value of T_INVESTOR_POSITION.FROZENCOMMISSION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getFrozencommission() {
        return frozencommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.FROZENCOMMISSION
     *
     * @param frozencommission the value for T_INVESTOR_POSITION.FROZENCOMMISSION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setFrozencommission(BigDecimal frozencommission) {
        this.frozencommission = frozencommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.CASHIN
     *
     * @return the value of T_INVESTOR_POSITION.CASHIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getCashin() {
        return cashin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.CASHIN
     *
     * @param cashin the value for T_INVESTOR_POSITION.CASHIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCashin(BigDecimal cashin) {
        this.cashin = cashin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.COMMISSION
     *
     * @return the value of T_INVESTOR_POSITION.COMMISSION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.COMMISSION
     *
     * @param commission the value for T_INVESTOR_POSITION.COMMISSION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.CLOSEPROFIT
     *
     * @return the value of T_INVESTOR_POSITION.CLOSEPROFIT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getCloseprofit() {
        return closeprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.CLOSEPROFIT
     *
     * @param closeprofit the value for T_INVESTOR_POSITION.CLOSEPROFIT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCloseprofit(BigDecimal closeprofit) {
        this.closeprofit = closeprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.POSITIONPROFIT
     *
     * @return the value of T_INVESTOR_POSITION.POSITIONPROFIT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getPositionprofit() {
        return positionprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.POSITIONPROFIT
     *
     * @param positionprofit the value for T_INVESTOR_POSITION.POSITIONPROFIT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPositionprofit(BigDecimal positionprofit) {
        this.positionprofit = positionprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.PRESETTLEMENTPRICE
     *
     * @return the value of T_INVESTOR_POSITION.PRESETTLEMENTPRICE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getPresettlementprice() {
        return presettlementprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.PRESETTLEMENTPRICE
     *
     * @param presettlementprice the value for T_INVESTOR_POSITION.PRESETTLEMENTPRICE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setPresettlementprice(BigDecimal presettlementprice) {
        this.presettlementprice = presettlementprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.SETTLEMENTPRICE
     *
     * @return the value of T_INVESTOR_POSITION.SETTLEMENTPRICE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getSettlementprice() {
        return settlementprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.SETTLEMENTPRICE
     *
     * @param settlementprice the value for T_INVESTOR_POSITION.SETTLEMENTPRICE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setSettlementprice(BigDecimal settlementprice) {
        this.settlementprice = settlementprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.TRADINGDAY
     *
     * @return the value of T_INVESTOR_POSITION.TRADINGDAY
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getTradingday() {
        return tradingday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.TRADINGDAY
     *
     * @param tradingday the value for T_INVESTOR_POSITION.TRADINGDAY
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setTradingday(String tradingday) {
        this.tradingday = tradingday == null ? null : tradingday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.SETTLEMENTID
     *
     * @return the value of T_INVESTOR_POSITION.SETTLEMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getSettlementid() {
        return settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.SETTLEMENTID
     *
     * @param settlementid the value for T_INVESTOR_POSITION.SETTLEMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setSettlementid(Long settlementid) {
        this.settlementid = settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.OPENCOST
     *
     * @return the value of T_INVESTOR_POSITION.OPENCOST
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getOpencost() {
        return opencost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.OPENCOST
     *
     * @param opencost the value for T_INVESTOR_POSITION.OPENCOST
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setOpencost(BigDecimal opencost) {
        this.opencost = opencost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.EXCHANGEMARGIN
     *
     * @return the value of T_INVESTOR_POSITION.EXCHANGEMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getExchangemargin() {
        return exchangemargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.EXCHANGEMARGIN
     *
     * @param exchangemargin the value for T_INVESTOR_POSITION.EXCHANGEMARGIN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setExchangemargin(BigDecimal exchangemargin) {
        this.exchangemargin = exchangemargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.COMBPOSITION
     *
     * @return the value of T_INVESTOR_POSITION.COMBPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getCombposition() {
        return combposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.COMBPOSITION
     *
     * @param combposition the value for T_INVESTOR_POSITION.COMBPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCombposition(Long combposition) {
        this.combposition = combposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.COMBLONGFROZEN
     *
     * @return the value of T_INVESTOR_POSITION.COMBLONGFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getComblongfrozen() {
        return comblongfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.COMBLONGFROZEN
     *
     * @param comblongfrozen the value for T_INVESTOR_POSITION.COMBLONGFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setComblongfrozen(Long comblongfrozen) {
        this.comblongfrozen = comblongfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.COMBSHORTFROZEN
     *
     * @return the value of T_INVESTOR_POSITION.COMBSHORTFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getCombshortfrozen() {
        return combshortfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.COMBSHORTFROZEN
     *
     * @param combshortfrozen the value for T_INVESTOR_POSITION.COMBSHORTFROZEN
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCombshortfrozen(Long combshortfrozen) {
        this.combshortfrozen = combshortfrozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.CLOSEPROFITBYDATE
     *
     * @return the value of T_INVESTOR_POSITION.CLOSEPROFITBYDATE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getCloseprofitbydate() {
        return closeprofitbydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.CLOSEPROFITBYDATE
     *
     * @param closeprofitbydate the value for T_INVESTOR_POSITION.CLOSEPROFITBYDATE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCloseprofitbydate(BigDecimal closeprofitbydate) {
        this.closeprofitbydate = closeprofitbydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.CLOSEPROFITBYTRADE
     *
     * @return the value of T_INVESTOR_POSITION.CLOSEPROFITBYTRADE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getCloseprofitbytrade() {
        return closeprofitbytrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.CLOSEPROFITBYTRADE
     *
     * @param closeprofitbytrade the value for T_INVESTOR_POSITION.CLOSEPROFITBYTRADE
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setCloseprofitbytrade(BigDecimal closeprofitbytrade) {
        this.closeprofitbytrade = closeprofitbytrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.TODAYPOSITION
     *
     * @return the value of T_INVESTOR_POSITION.TODAYPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public Long getTodayposition() {
        return todayposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.TODAYPOSITION
     *
     * @param todayposition the value for T_INVESTOR_POSITION.TODAYPOSITION
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setTodayposition(Long todayposition) {
        this.todayposition = todayposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.MARGINRATEBYMONEY
     *
     * @return the value of T_INVESTOR_POSITION.MARGINRATEBYMONEY
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getMarginratebymoney() {
        return marginratebymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.MARGINRATEBYMONEY
     *
     * @param marginratebymoney the value for T_INVESTOR_POSITION.MARGINRATEBYMONEY
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setMarginratebymoney(BigDecimal marginratebymoney) {
        this.marginratebymoney = marginratebymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.MARGINRATEBYVOLUME
     *
     * @return the value of T_INVESTOR_POSITION.MARGINRATEBYVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getMarginratebyvolume() {
        return marginratebyvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.MARGINRATEBYVOLUME
     *
     * @param marginratebyvolume the value for T_INVESTOR_POSITION.MARGINRATEBYVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setMarginratebyvolume(BigDecimal marginratebyvolume) {
        this.marginratebyvolume = marginratebyvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.SUBUSERID
     *
     * @return the value of T_INVESTOR_POSITION.SUBUSERID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getSubuserid() {
        return subuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.SUBUSERID
     *
     * @param subuserid the value for T_INVESTOR_POSITION.SUBUSERID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setSubuserid(String subuserid) {
        this.subuserid = subuserid == null ? null : subuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.FRONTID
     *
     * @return the value of T_INVESTOR_POSITION.FRONTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getFrontid() {
        return frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.FRONTID
     *
     * @param frontid the value for T_INVESTOR_POSITION.FRONTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setFrontid(BigDecimal frontid) {
        this.frontid = frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.SESSIONID
     *
     * @return the value of T_INVESTOR_POSITION.SESSIONID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.SESSIONID
     *
     * @param sessionid the value for T_INVESTOR_POSITION.SESSIONID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.ORDERREF
     *
     * @return the value of T_INVESTOR_POSITION.ORDERREF
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getOrderref() {
        return orderref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.ORDERREF
     *
     * @param orderref the value for T_INVESTOR_POSITION.ORDERREF
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setOrderref(String orderref) {
        this.orderref = orderref == null ? null : orderref.trim();
    }

	public BigDecimal getPositionWin() {
		return positionWin;
	}

	public void setPositionWin(BigDecimal positionWin) {
		this.positionWin = positionWin;
	}

	public BigDecimal getLastPrice() {
		return lastPrice;
	}

	public void setLastPrice(BigDecimal lastPrice) {
		this.lastPrice = lastPrice;
	}

	/**
	 * 买一价
	 * @return
	 */
	public BigDecimal getBidPrice1() {
		return bidPrice1;
	}

	/**
	 * 买一价
	 */
	public void setBidPrice1(BigDecimal bidPrice1) {
		this.bidPrice1 = bidPrice1;
	}

	/**
	 * 卖一价
	 * @return
	 */
	public BigDecimal getAskPrice1() {
		return askPrice1;
	}

	/**
	 * 卖一价
	 */
	public void setAskPrice1(BigDecimal askPrice1) {
		this.askPrice1 = askPrice1;
	}

	/**
     * 涨停价
     */
	public BigDecimal getUpperLimitPrice() {
		return upperLimitPrice;
	}

	/**
     * 涨停价
     */
	public void setUpperLimitPrice(BigDecimal upperLimitPrice) {
		this.upperLimitPrice = upperLimitPrice;
	}

	/**
     * 跌停价 
     */
	public BigDecimal getLowerLimitPrice() {
		return lowerLimitPrice;
	}

	/**
     * 跌停价 
     */
	public void setLowerLimitPrice(BigDecimal lowerLimitPrice) {
		this.lowerLimitPrice = lowerLimitPrice;
	}
	
	
}