package com.bohai.subAccount.entity;

import java.util.Date;

public class MainAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_ACCOUNT.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_ACCOUNT.ACCOUNT_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_ACCOUNT.PASSWD
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_ACCOUNT.BROKER_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String brokerId;
    
    /**
     * 前置机地址
     */
    private String frontAddress;
    
    /**
     * 账户类型   1：账户主 2：账户备
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_ACCOUNT.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MAIN_ACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date updateTime;

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_ACCOUNT.ID
     *
     * @return the value of T_MAIN_ACCOUNT.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_ACCOUNT.ID
     *
     * @param id the value for T_MAIN_ACCOUNT.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_ACCOUNT.ACCOUNT_NO
     *
     * @return the value of T_MAIN_ACCOUNT.ACCOUNT_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_ACCOUNT.ACCOUNT_NO
     *
     * @param accountNo the value for T_MAIN_ACCOUNT.ACCOUNT_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_ACCOUNT.PASSWD
     *
     * @return the value of T_MAIN_ACCOUNT.PASSWD
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_ACCOUNT.PASSWD
     *
     * @param passwd the value for T_MAIN_ACCOUNT.PASSWD
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_ACCOUNT.BROKER_ID
     *
     * @return the value of T_MAIN_ACCOUNT.BROKER_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getBrokerId() {
        return brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_ACCOUNT.BROKER_ID
     *
     * @param brokerId the value for T_MAIN_ACCOUNT.BROKER_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setBrokerId(String brokerId) {
        this.brokerId = brokerId == null ? null : brokerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_ACCOUNT.CREATE_TIME
     *
     * @return the value of T_MAIN_ACCOUNT.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_ACCOUNT.CREATE_TIME
     *
     * @param createTime the value for T_MAIN_ACCOUNT.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MAIN_ACCOUNT.UPDATE_TIME
     *
     * @return the value of T_MAIN_ACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MAIN_ACCOUNT.UPDATE_TIME
     *
     * @param updateTime the value for T_MAIN_ACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getFrontAddress() {
		return frontAddress;
	}

	public void setFrontAddress(String frontAddress) {
		this.frontAddress = frontAddress;
	}
    
}