package com.bohai.subAccount.entity;

import java.math.BigDecimal;

public class SubTradingaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.ACCOUNTID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.PREMORTGAGE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal premortgage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.PRECREDIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal precredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.PREDEPOSIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal predeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.PREBALANCE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal prebalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.PREMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal premargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.INTERESTBASE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal interestbase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.INTEREST
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.DEPOSIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.WITHDRAW
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal withdraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.FROZENMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal frozenmargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.FROZENCASH
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal frozencash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.FROZENCOMMISSION
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal frozencommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.CURRMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal currmargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.CASHIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal cashin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.COMMISSION
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.CLOSEPROFIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal closeprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.POSITIONPROFIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal positionprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.BALANCE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.AVAILABLE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.WITHDRAWQUOTA
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal withdrawquota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.RESERVE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.TRADINGDAY
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String tradingday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.SETTLEMENTID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private Long settlementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.CREDIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.MORTGAGE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal mortgage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.EXCHANGEMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal exchangemargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.DELIVERYMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal deliverymargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUB_TRADINGACCOUNT.EXCHANGEDELIVERYMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private BigDecimal exchangedeliverymargin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.ACCOUNTID
     *
     * @return the value of T_SUB_TRADINGACCOUNT.ACCOUNTID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.ACCOUNTID
     *
     * @param accountid the value for T_SUB_TRADINGACCOUNT.ACCOUNTID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.PREMORTGAGE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.PREMORTGAGE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getPremortgage() {
        return premortgage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.PREMORTGAGE
     *
     * @param premortgage the value for T_SUB_TRADINGACCOUNT.PREMORTGAGE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setPremortgage(BigDecimal premortgage) {
        this.premortgage = premortgage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.PRECREDIT
     *
     * @return the value of T_SUB_TRADINGACCOUNT.PRECREDIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getPrecredit() {
        return precredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.PRECREDIT
     *
     * @param precredit the value for T_SUB_TRADINGACCOUNT.PRECREDIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setPrecredit(BigDecimal precredit) {
        this.precredit = precredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.PREDEPOSIT
     *
     * @return the value of T_SUB_TRADINGACCOUNT.PREDEPOSIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getPredeposit() {
        return predeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.PREDEPOSIT
     *
     * @param predeposit the value for T_SUB_TRADINGACCOUNT.PREDEPOSIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setPredeposit(BigDecimal predeposit) {
        this.predeposit = predeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.PREBALANCE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.PREBALANCE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getPrebalance() {
        return prebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.PREBALANCE
     *
     * @param prebalance the value for T_SUB_TRADINGACCOUNT.PREBALANCE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setPrebalance(BigDecimal prebalance) {
        this.prebalance = prebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.PREMARGIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.PREMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getPremargin() {
        return premargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.PREMARGIN
     *
     * @param premargin the value for T_SUB_TRADINGACCOUNT.PREMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setPremargin(BigDecimal premargin) {
        this.premargin = premargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.INTERESTBASE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.INTERESTBASE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getInterestbase() {
        return interestbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.INTERESTBASE
     *
     * @param interestbase the value for T_SUB_TRADINGACCOUNT.INTERESTBASE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setInterestbase(BigDecimal interestbase) {
        this.interestbase = interestbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.INTEREST
     *
     * @return the value of T_SUB_TRADINGACCOUNT.INTEREST
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.INTEREST
     *
     * @param interest the value for T_SUB_TRADINGACCOUNT.INTEREST
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.DEPOSIT
     *
     * @return the value of T_SUB_TRADINGACCOUNT.DEPOSIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.DEPOSIT
     *
     * @param deposit the value for T_SUB_TRADINGACCOUNT.DEPOSIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.WITHDRAW
     *
     * @return the value of T_SUB_TRADINGACCOUNT.WITHDRAW
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getWithdraw() {
        return withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.WITHDRAW
     *
     * @param withdraw the value for T_SUB_TRADINGACCOUNT.WITHDRAW
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setWithdraw(BigDecimal withdraw) {
        this.withdraw = withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.FROZENMARGIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.FROZENMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getFrozenmargin() {
        return frozenmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.FROZENMARGIN
     *
     * @param frozenmargin the value for T_SUB_TRADINGACCOUNT.FROZENMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setFrozenmargin(BigDecimal frozenmargin) {
        this.frozenmargin = frozenmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.FROZENCASH
     *
     * @return the value of T_SUB_TRADINGACCOUNT.FROZENCASH
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getFrozencash() {
        return frozencash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.FROZENCASH
     *
     * @param frozencash the value for T_SUB_TRADINGACCOUNT.FROZENCASH
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setFrozencash(BigDecimal frozencash) {
        this.frozencash = frozencash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.FROZENCOMMISSION
     *
     * @return the value of T_SUB_TRADINGACCOUNT.FROZENCOMMISSION
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getFrozencommission() {
        return frozencommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.FROZENCOMMISSION
     *
     * @param frozencommission the value for T_SUB_TRADINGACCOUNT.FROZENCOMMISSION
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setFrozencommission(BigDecimal frozencommission) {
        this.frozencommission = frozencommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.CURRMARGIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.CURRMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getCurrmargin() {
        return currmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.CURRMARGIN
     *
     * @param currmargin the value for T_SUB_TRADINGACCOUNT.CURRMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setCurrmargin(BigDecimal currmargin) {
        this.currmargin = currmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.CASHIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.CASHIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getCashin() {
        return cashin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.CASHIN
     *
     * @param cashin the value for T_SUB_TRADINGACCOUNT.CASHIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setCashin(BigDecimal cashin) {
        this.cashin = cashin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.COMMISSION
     *
     * @return the value of T_SUB_TRADINGACCOUNT.COMMISSION
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.COMMISSION
     *
     * @param commission the value for T_SUB_TRADINGACCOUNT.COMMISSION
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.CLOSEPROFIT
     *
     * @return the value of T_SUB_TRADINGACCOUNT.CLOSEPROFIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getCloseprofit() {
        return closeprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.CLOSEPROFIT
     *
     * @param closeprofit the value for T_SUB_TRADINGACCOUNT.CLOSEPROFIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setCloseprofit(BigDecimal closeprofit) {
        this.closeprofit = closeprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.POSITIONPROFIT
     *
     * @return the value of T_SUB_TRADINGACCOUNT.POSITIONPROFIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getPositionprofit() {
        return positionprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.POSITIONPROFIT
     *
     * @param positionprofit the value for T_SUB_TRADINGACCOUNT.POSITIONPROFIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setPositionprofit(BigDecimal positionprofit) {
        this.positionprofit = positionprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.BALANCE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.BALANCE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.BALANCE
     *
     * @param balance the value for T_SUB_TRADINGACCOUNT.BALANCE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.AVAILABLE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.AVAILABLE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.AVAILABLE
     *
     * @param available the value for T_SUB_TRADINGACCOUNT.AVAILABLE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setAvailable(BigDecimal available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.WITHDRAWQUOTA
     *
     * @return the value of T_SUB_TRADINGACCOUNT.WITHDRAWQUOTA
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getWithdrawquota() {
        return withdrawquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.WITHDRAWQUOTA
     *
     * @param withdrawquota the value for T_SUB_TRADINGACCOUNT.WITHDRAWQUOTA
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setWithdrawquota(BigDecimal withdrawquota) {
        this.withdrawquota = withdrawquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.RESERVE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.RESERVE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.RESERVE
     *
     * @param reserve the value for T_SUB_TRADINGACCOUNT.RESERVE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setReserve(BigDecimal reserve) {
        this.reserve = reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.TRADINGDAY
     *
     * @return the value of T_SUB_TRADINGACCOUNT.TRADINGDAY
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getTradingday() {
        return tradingday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.TRADINGDAY
     *
     * @param tradingday the value for T_SUB_TRADINGACCOUNT.TRADINGDAY
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setTradingday(String tradingday) {
        this.tradingday = tradingday == null ? null : tradingday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.SETTLEMENTID
     *
     * @return the value of T_SUB_TRADINGACCOUNT.SETTLEMENTID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public Long getSettlementid() {
        return settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.SETTLEMENTID
     *
     * @param settlementid the value for T_SUB_TRADINGACCOUNT.SETTLEMENTID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setSettlementid(Long settlementid) {
        this.settlementid = settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.CREDIT
     *
     * @return the value of T_SUB_TRADINGACCOUNT.CREDIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.CREDIT
     *
     * @param credit the value for T_SUB_TRADINGACCOUNT.CREDIT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.MORTGAGE
     *
     * @return the value of T_SUB_TRADINGACCOUNT.MORTGAGE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getMortgage() {
        return mortgage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.MORTGAGE
     *
     * @param mortgage the value for T_SUB_TRADINGACCOUNT.MORTGAGE
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setMortgage(BigDecimal mortgage) {
        this.mortgage = mortgage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.EXCHANGEMARGIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.EXCHANGEMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getExchangemargin() {
        return exchangemargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.EXCHANGEMARGIN
     *
     * @param exchangemargin the value for T_SUB_TRADINGACCOUNT.EXCHANGEMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setExchangemargin(BigDecimal exchangemargin) {
        this.exchangemargin = exchangemargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.DELIVERYMARGIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.DELIVERYMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getDeliverymargin() {
        return deliverymargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.DELIVERYMARGIN
     *
     * @param deliverymargin the value for T_SUB_TRADINGACCOUNT.DELIVERYMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setDeliverymargin(BigDecimal deliverymargin) {
        this.deliverymargin = deliverymargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUB_TRADINGACCOUNT.EXCHANGEDELIVERYMARGIN
     *
     * @return the value of T_SUB_TRADINGACCOUNT.EXCHANGEDELIVERYMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public BigDecimal getExchangedeliverymargin() {
        return exchangedeliverymargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUB_TRADINGACCOUNT.EXCHANGEDELIVERYMARGIN
     *
     * @param exchangedeliverymargin the value for T_SUB_TRADINGACCOUNT.EXCHANGEDELIVERYMARGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setExchangedeliverymargin(BigDecimal exchangedeliverymargin) {
        this.exchangedeliverymargin = exchangedeliverymargin;
    }
}