package com.bohai.subAccount.entity;

import java.math.BigDecimal;

public class BuyDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.COMBOKEY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String combokey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.BROKERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String brokerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.INVESTORID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String investorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.INSTRUMENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String instrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.ORDERREF
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String orderref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.USERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.EXCHANGEID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String exchangeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADEID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.DIRECTION
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.ORDERSYSID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String ordersysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.PARTICIPANTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String participantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.CLIENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADINGROLE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradingrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.EXCHANGEINSTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String exchangeinstid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.OFFSETFLAG
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String offsetflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.HEDGEFLAG
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String hedgeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.PRICE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.VOLUME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private Short volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADEDATE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADETIME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADETYPE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.PRICESOURCE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String pricesource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String traderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.ORDERLOCALID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String orderlocalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.CLEARINGPARTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String clearingpartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.BUSINESSUNIT
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String businessunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.SEQUENCENO
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private Long sequenceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADINGDAY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradingday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.SETTLEMENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private Long settlementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.BROKERORDERSEQ
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private Long brokerorderseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.TRADESOURCE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String tradesource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.SUBUSERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String subuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.FRONTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private BigDecimal frontid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.SESSIONID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private BigDecimal sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.SELLCOMBOKEY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private String sellcombokey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BUY_DETAIL.SELLVOLUME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    private Long sellvolume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.COMBOKEY
     *
     * @return the value of T_BUY_DETAIL.COMBOKEY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getCombokey() {
        return combokey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.COMBOKEY
     *
     * @param combokey the value for T_BUY_DETAIL.COMBOKEY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setCombokey(String combokey) {
        this.combokey = combokey == null ? null : combokey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.BROKERID
     *
     * @return the value of T_BUY_DETAIL.BROKERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getBrokerid() {
        return brokerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.BROKERID
     *
     * @param brokerid the value for T_BUY_DETAIL.BROKERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setBrokerid(String brokerid) {
        this.brokerid = brokerid == null ? null : brokerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.INVESTORID
     *
     * @return the value of T_BUY_DETAIL.INVESTORID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getInvestorid() {
        return investorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.INVESTORID
     *
     * @param investorid the value for T_BUY_DETAIL.INVESTORID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setInvestorid(String investorid) {
        this.investorid = investorid == null ? null : investorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.INSTRUMENTID
     *
     * @return the value of T_BUY_DETAIL.INSTRUMENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getInstrumentid() {
        return instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.INSTRUMENTID
     *
     * @param instrumentid the value for T_BUY_DETAIL.INSTRUMENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setInstrumentid(String instrumentid) {
        this.instrumentid = instrumentid == null ? null : instrumentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.ORDERREF
     *
     * @return the value of T_BUY_DETAIL.ORDERREF
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getOrderref() {
        return orderref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.ORDERREF
     *
     * @param orderref the value for T_BUY_DETAIL.ORDERREF
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setOrderref(String orderref) {
        this.orderref = orderref == null ? null : orderref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.USERID
     *
     * @return the value of T_BUY_DETAIL.USERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.USERID
     *
     * @param userid the value for T_BUY_DETAIL.USERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.EXCHANGEID
     *
     * @return the value of T_BUY_DETAIL.EXCHANGEID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getExchangeid() {
        return exchangeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.EXCHANGEID
     *
     * @param exchangeid the value for T_BUY_DETAIL.EXCHANGEID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setExchangeid(String exchangeid) {
        this.exchangeid = exchangeid == null ? null : exchangeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADEID
     *
     * @return the value of T_BUY_DETAIL.TRADEID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADEID
     *
     * @param tradeid the value for T_BUY_DETAIL.TRADEID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradeid(String tradeid) {
        this.tradeid = tradeid == null ? null : tradeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.DIRECTION
     *
     * @return the value of T_BUY_DETAIL.DIRECTION
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.DIRECTION
     *
     * @param direction the value for T_BUY_DETAIL.DIRECTION
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.ORDERSYSID
     *
     * @return the value of T_BUY_DETAIL.ORDERSYSID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getOrdersysid() {
        return ordersysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.ORDERSYSID
     *
     * @param ordersysid the value for T_BUY_DETAIL.ORDERSYSID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setOrdersysid(String ordersysid) {
        this.ordersysid = ordersysid == null ? null : ordersysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.PARTICIPANTID
     *
     * @return the value of T_BUY_DETAIL.PARTICIPANTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getParticipantid() {
        return participantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.PARTICIPANTID
     *
     * @param participantid the value for T_BUY_DETAIL.PARTICIPANTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setParticipantid(String participantid) {
        this.participantid = participantid == null ? null : participantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.CLIENTID
     *
     * @return the value of T_BUY_DETAIL.CLIENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.CLIENTID
     *
     * @param clientid the value for T_BUY_DETAIL.CLIENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADINGROLE
     *
     * @return the value of T_BUY_DETAIL.TRADINGROLE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradingrole() {
        return tradingrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADINGROLE
     *
     * @param tradingrole the value for T_BUY_DETAIL.TRADINGROLE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradingrole(String tradingrole) {
        this.tradingrole = tradingrole == null ? null : tradingrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.EXCHANGEINSTID
     *
     * @return the value of T_BUY_DETAIL.EXCHANGEINSTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getExchangeinstid() {
        return exchangeinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.EXCHANGEINSTID
     *
     * @param exchangeinstid the value for T_BUY_DETAIL.EXCHANGEINSTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setExchangeinstid(String exchangeinstid) {
        this.exchangeinstid = exchangeinstid == null ? null : exchangeinstid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.OFFSETFLAG
     *
     * @return the value of T_BUY_DETAIL.OFFSETFLAG
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getOffsetflag() {
        return offsetflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.OFFSETFLAG
     *
     * @param offsetflag the value for T_BUY_DETAIL.OFFSETFLAG
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setOffsetflag(String offsetflag) {
        this.offsetflag = offsetflag == null ? null : offsetflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.HEDGEFLAG
     *
     * @return the value of T_BUY_DETAIL.HEDGEFLAG
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getHedgeflag() {
        return hedgeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.HEDGEFLAG
     *
     * @param hedgeflag the value for T_BUY_DETAIL.HEDGEFLAG
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setHedgeflag(String hedgeflag) {
        this.hedgeflag = hedgeflag == null ? null : hedgeflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.PRICE
     *
     * @return the value of T_BUY_DETAIL.PRICE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.PRICE
     *
     * @param price the value for T_BUY_DETAIL.PRICE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.VOLUME
     *
     * @return the value of T_BUY_DETAIL.VOLUME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public Short getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.VOLUME
     *
     * @param volume the value for T_BUY_DETAIL.VOLUME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setVolume(Short volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADEDATE
     *
     * @return the value of T_BUY_DETAIL.TRADEDATE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradedate() {
        return tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADEDATE
     *
     * @param tradedate the value for T_BUY_DETAIL.TRADEDATE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradedate(String tradedate) {
        this.tradedate = tradedate == null ? null : tradedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADETIME
     *
     * @return the value of T_BUY_DETAIL.TRADETIME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradetime() {
        return tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADETIME
     *
     * @param tradetime the value for T_BUY_DETAIL.TRADETIME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradetime(String tradetime) {
        this.tradetime = tradetime == null ? null : tradetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADETYPE
     *
     * @return the value of T_BUY_DETAIL.TRADETYPE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradetype() {
        return tradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADETYPE
     *
     * @param tradetype the value for T_BUY_DETAIL.TRADETYPE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradetype(String tradetype) {
        this.tradetype = tradetype == null ? null : tradetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.PRICESOURCE
     *
     * @return the value of T_BUY_DETAIL.PRICESOURCE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getPricesource() {
        return pricesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.PRICESOURCE
     *
     * @param pricesource the value for T_BUY_DETAIL.PRICESOURCE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setPricesource(String pricesource) {
        this.pricesource = pricesource == null ? null : pricesource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADERID
     *
     * @return the value of T_BUY_DETAIL.TRADERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTraderid() {
        return traderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADERID
     *
     * @param traderid the value for T_BUY_DETAIL.TRADERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTraderid(String traderid) {
        this.traderid = traderid == null ? null : traderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.ORDERLOCALID
     *
     * @return the value of T_BUY_DETAIL.ORDERLOCALID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getOrderlocalid() {
        return orderlocalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.ORDERLOCALID
     *
     * @param orderlocalid the value for T_BUY_DETAIL.ORDERLOCALID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setOrderlocalid(String orderlocalid) {
        this.orderlocalid = orderlocalid == null ? null : orderlocalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.CLEARINGPARTID
     *
     * @return the value of T_BUY_DETAIL.CLEARINGPARTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getClearingpartid() {
        return clearingpartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.CLEARINGPARTID
     *
     * @param clearingpartid the value for T_BUY_DETAIL.CLEARINGPARTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setClearingpartid(String clearingpartid) {
        this.clearingpartid = clearingpartid == null ? null : clearingpartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.BUSINESSUNIT
     *
     * @return the value of T_BUY_DETAIL.BUSINESSUNIT
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getBusinessunit() {
        return businessunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.BUSINESSUNIT
     *
     * @param businessunit the value for T_BUY_DETAIL.BUSINESSUNIT
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setBusinessunit(String businessunit) {
        this.businessunit = businessunit == null ? null : businessunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.SEQUENCENO
     *
     * @return the value of T_BUY_DETAIL.SEQUENCENO
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public Long getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.SEQUENCENO
     *
     * @param sequenceno the value for T_BUY_DETAIL.SEQUENCENO
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setSequenceno(Long sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADINGDAY
     *
     * @return the value of T_BUY_DETAIL.TRADINGDAY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradingday() {
        return tradingday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADINGDAY
     *
     * @param tradingday the value for T_BUY_DETAIL.TRADINGDAY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradingday(String tradingday) {
        this.tradingday = tradingday == null ? null : tradingday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.SETTLEMENTID
     *
     * @return the value of T_BUY_DETAIL.SETTLEMENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public Long getSettlementid() {
        return settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.SETTLEMENTID
     *
     * @param settlementid the value for T_BUY_DETAIL.SETTLEMENTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setSettlementid(Long settlementid) {
        this.settlementid = settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.BROKERORDERSEQ
     *
     * @return the value of T_BUY_DETAIL.BROKERORDERSEQ
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public Long getBrokerorderseq() {
        return brokerorderseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.BROKERORDERSEQ
     *
     * @param brokerorderseq the value for T_BUY_DETAIL.BROKERORDERSEQ
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setBrokerorderseq(Long brokerorderseq) {
        this.brokerorderseq = brokerorderseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.TRADESOURCE
     *
     * @return the value of T_BUY_DETAIL.TRADESOURCE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getTradesource() {
        return tradesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.TRADESOURCE
     *
     * @param tradesource the value for T_BUY_DETAIL.TRADESOURCE
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setTradesource(String tradesource) {
        this.tradesource = tradesource == null ? null : tradesource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.SUBUSERID
     *
     * @return the value of T_BUY_DETAIL.SUBUSERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getSubuserid() {
        return subuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.SUBUSERID
     *
     * @param subuserid the value for T_BUY_DETAIL.SUBUSERID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setSubuserid(String subuserid) {
        this.subuserid = subuserid == null ? null : subuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.FRONTID
     *
     * @return the value of T_BUY_DETAIL.FRONTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public BigDecimal getFrontid() {
        return frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.FRONTID
     *
     * @param frontid the value for T_BUY_DETAIL.FRONTID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setFrontid(BigDecimal frontid) {
        this.frontid = frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.SESSIONID
     *
     * @return the value of T_BUY_DETAIL.SESSIONID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public BigDecimal getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.SESSIONID
     *
     * @param sessionid the value for T_BUY_DETAIL.SESSIONID
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.SELLCOMBOKEY
     *
     * @return the value of T_BUY_DETAIL.SELLCOMBOKEY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public String getSellcombokey() {
        return sellcombokey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.SELLCOMBOKEY
     *
     * @param sellcombokey the value for T_BUY_DETAIL.SELLCOMBOKEY
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setSellcombokey(String sellcombokey) {
        this.sellcombokey = sellcombokey == null ? null : sellcombokey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BUY_DETAIL.SELLVOLUME
     *
     * @return the value of T_BUY_DETAIL.SELLVOLUME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public Long getSellvolume() {
        return sellvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BUY_DETAIL.SELLVOLUME
     *
     * @param sellvolume the value for T_BUY_DETAIL.SELLVOLUME
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    public void setSellvolume(Long sellvolume) {
        this.sellvolume = sellvolume;
    }
}