package com.bohai.subAccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CapitalRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.USER_NAME
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.USER_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal userCapitalRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.USER_CAPITAL
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal userCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.HOST_CAPITAL1
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal hostCapital1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.UPDATE_TIME
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.HOST_CAPITAL2
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal hostCapital2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.HOST_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal hostCapitalRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.USER_OUT_CAPITAL_RETAIN
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal userOutCapitalRetain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CAPITAL_RATE.USER_CAPITAL_YESTORDAY
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    private BigDecimal userCapitalYestorday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.USER_NAME
     *
     * @return the value of T_CAPITAL_RATE.USER_NAME
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.USER_NAME
     *
     * @param userName the value for T_CAPITAL_RATE.USER_NAME
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.USER_CAPITAL_RATE
     *
     * @return the value of T_CAPITAL_RATE.USER_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getUserCapitalRate() {
        return userCapitalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.USER_CAPITAL_RATE
     *
     * @param userCapitalRate the value for T_CAPITAL_RATE.USER_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setUserCapitalRate(BigDecimal userCapitalRate) {
        this.userCapitalRate = userCapitalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.USER_CAPITAL
     *
     * @return the value of T_CAPITAL_RATE.USER_CAPITAL
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getUserCapital() {
        return userCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.USER_CAPITAL
     *
     * @param userCapital the value for T_CAPITAL_RATE.USER_CAPITAL
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setUserCapital(BigDecimal userCapital) {
        this.userCapital = userCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.HOST_CAPITAL1
     *
     * @return the value of T_CAPITAL_RATE.HOST_CAPITAL1
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getHostCapital1() {
        return hostCapital1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.HOST_CAPITAL1
     *
     * @param hostCapital1 the value for T_CAPITAL_RATE.HOST_CAPITAL1
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setHostCapital1(BigDecimal hostCapital1) {
        this.hostCapital1 = hostCapital1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.UPDATE_TIME
     *
     * @return the value of T_CAPITAL_RATE.UPDATE_TIME
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.UPDATE_TIME
     *
     * @param updateTime the value for T_CAPITAL_RATE.UPDATE_TIME
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.HOST_CAPITAL2
     *
     * @return the value of T_CAPITAL_RATE.HOST_CAPITAL2
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getHostCapital2() {
        return hostCapital2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.HOST_CAPITAL2
     *
     * @param hostCapital2 the value for T_CAPITAL_RATE.HOST_CAPITAL2
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setHostCapital2(BigDecimal hostCapital2) {
        this.hostCapital2 = hostCapital2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.HOST_CAPITAL_RATE
     *
     * @return the value of T_CAPITAL_RATE.HOST_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getHostCapitalRate() {
        return hostCapitalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.HOST_CAPITAL_RATE
     *
     * @param hostCapitalRate the value for T_CAPITAL_RATE.HOST_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setHostCapitalRate(BigDecimal hostCapitalRate) {
        this.hostCapitalRate = hostCapitalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.USER_OUT_CAPITAL_RETAIN
     *
     * @return the value of T_CAPITAL_RATE.USER_OUT_CAPITAL_RETAIN
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getUserOutCapitalRetain() {
        return userOutCapitalRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.USER_OUT_CAPITAL_RETAIN
     *
     * @param userOutCapitalRetain the value for T_CAPITAL_RATE.USER_OUT_CAPITAL_RETAIN
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setUserOutCapitalRetain(BigDecimal userOutCapitalRetain) {
        this.userOutCapitalRetain = userOutCapitalRetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CAPITAL_RATE.USER_CAPITAL_YESTORDAY
     *
     * @return the value of T_CAPITAL_RATE.USER_CAPITAL_YESTORDAY
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public BigDecimal getUserCapitalYestorday() {
        return userCapitalYestorday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CAPITAL_RATE.USER_CAPITAL_YESTORDAY
     *
     * @param userCapitalYestorday the value for T_CAPITAL_RATE.USER_CAPITAL_YESTORDAY
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    public void setUserCapitalYestorday(BigDecimal userCapitalYestorday) {
        this.userCapitalYestorday = userCapitalYestorday;
    }
}