package com.bohai.subAccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CloseRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.ID
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.HOP
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private Integer hop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.FORCE_CLOSE_RATE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private BigDecimal forceCloseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.CREATE_TIME
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.UPDATE_TIME
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.TICK_SIZE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private BigDecimal tickSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CLOSE_RULE.CONTRACT_NO
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    private String contractNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.ID
     *
     * @return the value of T_CLOSE_RULE.ID
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.ID
     *
     * @param id the value for T_CLOSE_RULE.ID
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.HOP
     *
     * @return the value of T_CLOSE_RULE.HOP
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public Integer getHop() {
        return hop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.HOP
     *
     * @param hop the value for T_CLOSE_RULE.HOP
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setHop(Integer hop) {
        this.hop = hop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.FORCE_CLOSE_RATE
     *
     * @return the value of T_CLOSE_RULE.FORCE_CLOSE_RATE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public BigDecimal getForceCloseRate() {
        return forceCloseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.FORCE_CLOSE_RATE
     *
     * @param forceCloseRate the value for T_CLOSE_RULE.FORCE_CLOSE_RATE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setForceCloseRate(BigDecimal forceCloseRate) {
        this.forceCloseRate = forceCloseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.CREATE_TIME
     *
     * @return the value of T_CLOSE_RULE.CREATE_TIME
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.CREATE_TIME
     *
     * @param createTime the value for T_CLOSE_RULE.CREATE_TIME
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.UPDATE_TIME
     *
     * @return the value of T_CLOSE_RULE.UPDATE_TIME
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.UPDATE_TIME
     *
     * @param updateTime the value for T_CLOSE_RULE.UPDATE_TIME
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.TICK_SIZE
     *
     * @return the value of T_CLOSE_RULE.TICK_SIZE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public BigDecimal getTickSize() {
        return tickSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.TICK_SIZE
     *
     * @param tickSize the value for T_CLOSE_RULE.TICK_SIZE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setTickSize(BigDecimal tickSize) {
        this.tickSize = tickSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CLOSE_RULE.CONTRACT_NO
     *
     * @return the value of T_CLOSE_RULE.CONTRACT_NO
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CLOSE_RULE.CONTRACT_NO
     *
     * @param contractNo the value for T_CLOSE_RULE.CONTRACT_NO
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }
}