package com.bohai.subAccount.entity;

import java.math.BigDecimal;

public class InvestorPosition2 {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String instrumentid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.LONGFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal tradingvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.SHORTFROZENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal averageposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal primecost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.CLOSEVOLUME
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal adjustablequantity;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private String posidirection;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_INVESTOR_POSITION.OPENAMOUNT
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    private BigDecimal openamount;
    
    private BigDecimal closeamount;
    
    private BigDecimal closevolume;
    
    private BigDecimal positionprofit;
    
    private BigDecimal closeprofit;
    private BigDecimal usemargin;
    private BigDecimal commission;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @return the value of T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public String getInstrumentid() {
        return instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @param instrumentid the value for T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setInstrumentid(String instrumentid) {
        this.instrumentid = instrumentid == null ? null : instrumentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @return the value of T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public BigDecimal getTradingvolume() {
        return tradingvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @param instrumentid the value for T_INVESTOR_POSITION.INSTRUMENTID
     *
     * @mbggenerated Mon Feb 20 16:25:22 CST 2017
     */
    public void setTradingvolume(BigDecimal tradingvolume) {
    	
    	this.tradingvolume = tradingvolume;
    }

    
    public BigDecimal getAverageposition() {
        return averageposition;
    }
    
    public void setAverageposition(BigDecimal averageposition) {
    	
    	this.averageposition = averageposition;
    }
    
    public BigDecimal getPrimecost() {
        return primecost;
    }
    
    public void setPrimecost(BigDecimal primecost) {
    	
    	this.primecost = primecost;
    }
    
    public BigDecimal getPosition() {
        return position;
    }
    
    public void setPosition(BigDecimal position) {
    	
    	this.position = position;
    }
    
    public BigDecimal getAdjustablequantity() {
        return adjustablequantity;
    }
    
    public void setAdjustablequantity(BigDecimal adjustablequantity) {
    	
    	this.adjustablequantity = adjustablequantity;
    }

    public String getPosidirection() {
        return posidirection;
    }
    
    public void setPosidirection(String posidirection) {
    	
    	this.posidirection = posidirection;
    }
    
    public BigDecimal getOpenamount() {
        return openamount;
    }
    
    public void setOpenamount(BigDecimal openamount) {
    	
    	this.openamount = openamount;
    }
    
    public BigDecimal getCloseamount() {
        return closeamount;
    }
    
    public void setCloseamount(BigDecimal closeamount) {
    	
    	this.closeamount = closeamount;
    }
    
    public BigDecimal getClosevolume() {
        return closevolume;
    }
    
    public void setClosevolume(BigDecimal closevolume) {
    	
    	this.closevolume = closevolume;
    }
    
    public BigDecimal getPositionprofit() {
        return positionprofit;
    }
    
    public void setPositionprofit(BigDecimal positionprofit) {
    	
    	this.positionprofit = positionprofit;
    }
    
    public BigDecimal getCloseprofit() {
        return closeprofit;
    }
    
    public void setCloseprofit(BigDecimal closeprofit) {
    	
    	this.closeprofit = closeprofit;
    }
    
    public BigDecimal getUsemargin() {
        return usemargin;
    }
    
    public void setUsemargin(BigDecimal usemargin) {
    	
    	this.usemargin = usemargin;
    }
    
    public BigDecimal getCommission() {
        return commission;
    }
    
    public void setCommission(BigDecimal commission) {
    	
    	this.commission = commission;
    }

}