package com.bohai.subAccount.entity;

import java.util.Date;

public class TradeRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.GROUP_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.CANCEL_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Integer cancelCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.ENTRUST_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Integer entrustCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.OPEN_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Integer openCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE_RULE.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.ID
     *
     * @return the value of T_TRADE_RULE.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.ID
     *
     * @param id the value for T_TRADE_RULE.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.GROUP_ID
     *
     * @return the value of T_TRADE_RULE.GROUP_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.GROUP_ID
     *
     * @param groupId the value for T_TRADE_RULE.GROUP_ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.CONTRACT
     *
     * @return the value of T_TRADE_RULE.CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.CONTRACT
     *
     * @param contract the value for T_TRADE_RULE.CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.CANCEL_COUNT
     *
     * @return the value of T_TRADE_RULE.CANCEL_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Integer getCancelCount() {
        return cancelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.CANCEL_COUNT
     *
     * @param cancelCount the value for T_TRADE_RULE.CANCEL_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCancelCount(Integer cancelCount) {
        this.cancelCount = cancelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.ENTRUST_COUNT
     *
     * @return the value of T_TRADE_RULE.ENTRUST_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Integer getEntrustCount() {
        return entrustCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.ENTRUST_COUNT
     *
     * @param entrustCount the value for T_TRADE_RULE.ENTRUST_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setEntrustCount(Integer entrustCount) {
        this.entrustCount = entrustCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.OPEN_COUNT
     *
     * @return the value of T_TRADE_RULE.OPEN_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Integer getOpenCount() {
        return openCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.OPEN_COUNT
     *
     * @param openCount the value for T_TRADE_RULE.OPEN_COUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setOpenCount(Integer openCount) {
        this.openCount = openCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.CREATE_TIME
     *
     * @return the value of T_TRADE_RULE.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.CREATE_TIME
     *
     * @param createTime the value for T_TRADE_RULE.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE_RULE.UPDATE_TIME
     *
     * @return the value of T_TRADE_RULE.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE_RULE.UPDATE_TIME
     *
     * @param updateTime the value for T_TRADE_RULE.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}