package com.bohai.subAccount.entity;

public class Trade2 {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TRADE.VOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long volume;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TRADE.VOLUME
     *
     * @return the value of T_TRADE.VOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TRADE.VOLUME
     *
     * @param volume the value for T_TRADE.VOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }
}