package com.bohai.subAccount.entity;

import java.math.BigDecimal;

public class Useravailableindb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.USERNAME
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.AVAILABLE
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.CLOSEWIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal closewin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.POSITIONWIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal positionwin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.COMMISSION
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.FROZENAVAILABLE
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal frozenavailable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.MARGIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal margin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USERAVAILABLEINDB.INOUTMONEY
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    private BigDecimal inoutmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.USERNAME
     *
     * @return the value of T_USERAVAILABLEINDB.USERNAME
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.USERNAME
     *
     * @param username the value for T_USERAVAILABLEINDB.USERNAME
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.AVAILABLE
     *
     * @return the value of T_USERAVAILABLEINDB.AVAILABLE
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.AVAILABLE
     *
     * @param available the value for T_USERAVAILABLEINDB.AVAILABLE
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setAvailable(BigDecimal available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.CLOSEWIN
     *
     * @return the value of T_USERAVAILABLEINDB.CLOSEWIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getClosewin() {
        return closewin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.CLOSEWIN
     *
     * @param closewin the value for T_USERAVAILABLEINDB.CLOSEWIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setClosewin(BigDecimal closewin) {
        this.closewin = closewin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.POSITIONWIN
     *
     * @return the value of T_USERAVAILABLEINDB.POSITIONWIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getPositionwin() {
        return positionwin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.POSITIONWIN
     *
     * @param positionwin the value for T_USERAVAILABLEINDB.POSITIONWIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setPositionwin(BigDecimal positionwin) {
        this.positionwin = positionwin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.COMMISSION
     *
     * @return the value of T_USERAVAILABLEINDB.COMMISSION
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.COMMISSION
     *
     * @param commission the value for T_USERAVAILABLEINDB.COMMISSION
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.FROZENAVAILABLE
     *
     * @return the value of T_USERAVAILABLEINDB.FROZENAVAILABLE
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getFrozenavailable() {
        return frozenavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.FROZENAVAILABLE
     *
     * @param frozenavailable the value for T_USERAVAILABLEINDB.FROZENAVAILABLE
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setFrozenavailable(BigDecimal frozenavailable) {
        this.frozenavailable = frozenavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.MARGIN
     *
     * @return the value of T_USERAVAILABLEINDB.MARGIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.MARGIN
     *
     * @param margin the value for T_USERAVAILABLEINDB.MARGIN
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setMargin(BigDecimal margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USERAVAILABLEINDB.INOUTMONEY
     *
     * @return the value of T_USERAVAILABLEINDB.INOUTMONEY
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public BigDecimal getInoutmoney() {
        return inoutmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USERAVAILABLEINDB.INOUTMONEY
     *
     * @param inoutmoney the value for T_USERAVAILABLEINDB.INOUTMONEY
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    public void setInoutmoney(BigDecimal inoutmoney) {
        this.inoutmoney = inoutmoney;
    }
}