package com.bohai.subAccount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserFrozenaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.USER_NO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.USER_NAME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.GROUP_ID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.FRONTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal frontid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.SESSIONID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.ORDERREF
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String orderref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.FROZENMARGIN
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal frozenmargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.FROZENCASH
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal frozencash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.FROZENCOMMISSION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal frozencommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.OFFSETFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String offsetflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.FROZEN_FLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String frozenFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.VOLUMETOTALORIGINAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long volumetotaloriginal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_FROZENACCOUNT.LIMITPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal limitprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.USER_NO
     *
     * @return the value of T_USER_FROZENACCOUNT.USER_NO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.USER_NO
     *
     * @param userNo the value for T_USER_FROZENACCOUNT.USER_NO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.USER_NAME
     *
     * @return the value of T_USER_FROZENACCOUNT.USER_NAME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.USER_NAME
     *
     * @param userName the value for T_USER_FROZENACCOUNT.USER_NAME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.GROUP_ID
     *
     * @return the value of T_USER_FROZENACCOUNT.GROUP_ID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.GROUP_ID
     *
     * @param groupId the value for T_USER_FROZENACCOUNT.GROUP_ID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.FRONTID
     *
     * @return the value of T_USER_FROZENACCOUNT.FRONTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getFrontid() {
        return frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.FRONTID
     *
     * @param frontid the value for T_USER_FROZENACCOUNT.FRONTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setFrontid(BigDecimal frontid) {
        this.frontid = frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.SESSIONID
     *
     * @return the value of T_USER_FROZENACCOUNT.SESSIONID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.SESSIONID
     *
     * @param sessionid the value for T_USER_FROZENACCOUNT.SESSIONID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.ORDERREF
     *
     * @return the value of T_USER_FROZENACCOUNT.ORDERREF
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrderref() {
        return orderref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.ORDERREF
     *
     * @param orderref the value for T_USER_FROZENACCOUNT.ORDERREF
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrderref(String orderref) {
        this.orderref = orderref == null ? null : orderref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.FROZENMARGIN
     *
     * @return the value of T_USER_FROZENACCOUNT.FROZENMARGIN
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getFrozenmargin() {
        return frozenmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.FROZENMARGIN
     *
     * @param frozenmargin the value for T_USER_FROZENACCOUNT.FROZENMARGIN
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setFrozenmargin(BigDecimal frozenmargin) {
        this.frozenmargin = frozenmargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.FROZENCASH
     *
     * @return the value of T_USER_FROZENACCOUNT.FROZENCASH
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getFrozencash() {
        return frozencash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.FROZENCASH
     *
     * @param frozencash the value for T_USER_FROZENACCOUNT.FROZENCASH
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setFrozencash(BigDecimal frozencash) {
        this.frozencash = frozencash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.FROZENCOMMISSION
     *
     * @return the value of T_USER_FROZENACCOUNT.FROZENCOMMISSION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getFrozencommission() {
        return frozencommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.FROZENCOMMISSION
     *
     * @param frozencommission the value for T_USER_FROZENACCOUNT.FROZENCOMMISSION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setFrozencommission(BigDecimal frozencommission) {
        this.frozencommission = frozencommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.OFFSETFLAG
     *
     * @return the value of T_USER_FROZENACCOUNT.OFFSETFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOffsetflag() {
        return offsetflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.OFFSETFLAG
     *
     * @param offsetflag the value for T_USER_FROZENACCOUNT.OFFSETFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOffsetflag(String offsetflag) {
        this.offsetflag = offsetflag == null ? null : offsetflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.FROZEN_FLAG
     *
     * @return the value of T_USER_FROZENACCOUNT.FROZEN_FLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getFrozenFlag() {
        return frozenFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.FROZEN_FLAG
     *
     * @param frozenFlag the value for T_USER_FROZENACCOUNT.FROZEN_FLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setFrozenFlag(String frozenFlag) {
        this.frozenFlag = frozenFlag == null ? null : frozenFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.UPDATE_TIME
     *
     * @return the value of T_USER_FROZENACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.UPDATE_TIME
     *
     * @param updateTime the value for T_USER_FROZENACCOUNT.UPDATE_TIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.VOLUMETOTALORIGINAL
     *
     * @return the value of T_USER_FROZENACCOUNT.VOLUMETOTALORIGINAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getVolumetotaloriginal() {
        return volumetotaloriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.VOLUMETOTALORIGINAL
     *
     * @param volumetotaloriginal the value for T_USER_FROZENACCOUNT.VOLUMETOTALORIGINAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setVolumetotaloriginal(Long volumetotaloriginal) {
        this.volumetotaloriginal = volumetotaloriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_FROZENACCOUNT.LIMITPRICE
     *
     * @return the value of T_USER_FROZENACCOUNT.LIMITPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getLimitprice() {
        return limitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_FROZENACCOUNT.LIMITPRICE
     *
     * @param limitprice the value for T_USER_FROZENACCOUNT.LIMITPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setLimitprice(BigDecimal limitprice) {
        this.limitprice = limitprice;
    }
}