package com.bohai.subAccount.entity;

import java.util.Date;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN.USER_NO
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN.USER_NAME
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN.USER_PWD
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN.GROUP_ID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN.LOGIN_FLG
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private String loginFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN.USER_NO
     *
     * @return the value of T_USER_LOGIN.USER_NO
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN.USER_NO
     *
     * @param userNo the value for T_USER_LOGIN.USER_NO
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN.USER_NAME
     *
     * @return the value of T_USER_LOGIN.USER_NAME
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN.USER_NAME
     *
     * @param userName the value for T_USER_LOGIN.USER_NAME
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN.USER_PWD
     *
     * @return the value of T_USER_LOGIN.USER_PWD
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN.USER_PWD
     *
     * @param userPwd the value for T_USER_LOGIN.USER_PWD
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN.GROUP_ID
     *
     * @return the value of T_USER_LOGIN.GROUP_ID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN.GROUP_ID
     *
     * @param groupId the value for T_USER_LOGIN.GROUP_ID
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN.LOGIN_FLG
     *
     * @return the value of T_USER_LOGIN.LOGIN_FLG
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public String getLoginFlg() {
        return loginFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN.LOGIN_FLG
     *
     * @param loginFlg the value for T_USER_LOGIN.LOGIN_FLG
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setLoginFlg(String loginFlg) {
        this.loginFlg = loginFlg == null ? null : loginFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN.UPDATE_TIME
     *
     * @return the value of T_USER_LOGIN.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN.UPDATE_TIME
     *
     * @param updateTime the value for T_USER_LOGIN.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}