package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.BuyDetail;

public interface BuyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUY_DETAIL
     *
     * @mbggenerated Sun Jun 04 12:42:18 CST 2017
     */
    int insert(BuyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUY_DETAIL
     *
     * @mbggenerated Sun Jun 04 12:42:18 CST 2017
     */
    int insertSelective(BuyDetail record);
}