package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.BuysellDetail;
import java.math.BigDecimal;

public interface BuysellDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUYSELL_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:56 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUYSELL_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:56 CST 2017
     */
    int insert(BuysellDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUYSELL_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:56 CST 2017
     */
    int insertSelective(BuysellDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUYSELL_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:56 CST 2017
     */
    BuysellDetail selectByPrimaryKey(BigDecimal seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUYSELL_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:56 CST 2017
     */
    int updateByPrimaryKeySelective(BuysellDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BUYSELL_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:56 CST 2017
     */
    int updateByPrimaryKey(BuysellDetail record);
}