package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.CapitalRateDetail;

public interface CapitalRateDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sat Apr 22 17:28:32 CST 2017
     */
    int insert(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sat Apr 22 17:28:32 CST 2017
     */
    int insertSelective(CapitalRateDetail record);
}