package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.CapitalRate;

public interface CapitalRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sat Apr 22 17:28:32 CST 2017
     */
    int insert(CapitalRate record);
    
    int update(CapitalRate record);
    
    int delete(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sat Apr 22 17:28:32 CST 2017
     */
    int insertSelective(CapitalRate record);
    
    CapitalRate getUserByUserName(String userName);
}