package com.bohai.subAccount.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;

import com.bohai.subAccount.entity.CloseRule;

public interface CloseRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_RULE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_RULE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    int insert(CloseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_RULE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    int insertSelective(CloseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_RULE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    CloseRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_RULE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    int updateByPrimaryKeySelective(CloseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_RULE
     *
     * @mbggenerated Tue Feb 07 16:50:51 CST 2017
     */
    int updateByPrimaryKey(CloseRule record);
    
    List<CloseRule> getAllCloseRule();
    
    List<CloseRule> getCloseRuleByUserNo(String userNo);
    
    int deleteByContractNo(String contractNo);
    
    @Delete("delete from T_CLOSE_RULE t where exists (select 1 from t_user_contract t1 where t1.user_no = #{0} and t.contract_no = t1.contract_no)")
    int deleteByUserNo(String userNo);
}