package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.CloseDetail;
import java.math.BigDecimal;

public interface CloseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:57 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:57 CST 2017
     */
    int insert(CloseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:57 CST 2017
     */
    int insertSelective(CloseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:57 CST 2017
     */
    CloseDetail selectByPrimaryKey(BigDecimal seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:57 CST 2017
     */
    int updateByPrimaryKeySelective(CloseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CLOSE_DETAIL
     *
     * @mbggenerated Sat May 20 15:35:57 CST 2017
     */
    int updateByPrimaryKey(CloseDetail record);
}