package com.bohai.subAccount.dao;

import java.util.List;

import com.bohai.subAccount.entity.Ctptradingaccount;
import com.bohai.subAccount.entity.InputOrder;

public interface CtptradingaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTPTRADINGACCOUNT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    int insert(Ctptradingaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTPTRADINGACCOUNT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    int insertSelective(Ctptradingaccount record);
    
    int update(Ctptradingaccount record);
    
    List<Ctptradingaccount> getUserByUserName(String username);
    
    int delete(String username);
}