package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.FutureMarket;

public interface FutureMarketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FUTURE_MARKET
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    int insert(FutureMarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FUTURE_MARKET
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    int insertSelective(FutureMarket record);
}