package com.bohai.subAccount.dao;

import java.util.List;

import com.bohai.subAccount.entity.GroupInfo;

public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    GroupInfo selectByPrimaryKey(String id);
    
    /**
     * 查询所有用户组
     * @return
     */
    List<GroupInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKey(GroupInfo record);
}