package com.bohai.subAccount.dao;

import org.apache.ibatis.annotations.Insert;

import com.bohai.subAccount.entity.InputOrderHistory;

public interface InputOrderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INPUT_ORDER_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insert(InputOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INPUT_ORDER_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insertSelective(InputOrderHistory record);
    
    @Insert("insert into t_input_order_history select t.*,to_char(sysdate,'yyyymmdd') from t_input_order t")
    int backup();
}