package com.bohai.subAccount.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.bohai.subAccount.entity.MainAccount;

public interface MainAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insert(MainAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insertSelective(MainAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    MainAccount selectByPrimaryKey(String id);
    
    List<MainAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKeySelective(MainAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MAIN_ACCOUNT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKey(MainAccount record);
    
    @Select("select count(1) from t_main_account where account_type = #{accountType}")
    Integer selectCount();
}