package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.SellDetail;

public interface SellDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SELL_DETAIL
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    int insert(SellDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SELL_DETAIL
     *
     * @mbggenerated Sun Jun 04 13:56:33 CST 2017
     */
    int insertSelective(SellDetail record);
}