package com.bohai.subAccount.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;

import com.bohai.subAccount.entity.InputOrder;
import com.bohai.subAccount.entity.SubTradingaccount;

public interface SubTradingaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUB_TRADINGACCOUNT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    int insert(SubTradingaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUB_TRADINGACCOUNT
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    int insertSelective(SubTradingaccount record);
    
    int update(SubTradingaccount record);
    
    List<SubTradingaccount> getUserByUserName(String subuserid);
    
    int delete(String subuserid);
    
    SubTradingaccount getUserByUserName2(String subuserid);
    
    int setFrozen(Map<String,Object> map);
    
    List<SubTradingaccount> getUserByAllForAccount();
    
    int updateUnfrozen(Map<String,Object> map);
    
    int setCommission(Map<String,Object> map);
    
    /**
     * 数据初始化
     * @return 更新条数
     */
    int init();
}