package com.bohai.subAccount.dao;

import org.apache.ibatis.annotations.Insert;

import com.bohai.subAccount.entity.TradeHistory;

public interface TradeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insert(TradeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insertSelective(TradeHistory record);
    
    @Insert("insert into t_trade_history select t.*,to_char(sysdate,'yyyymmdd') from t_trade t")
    int backup();
}