package com.bohai.subAccount.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;

import com.bohai.subAccount.entity.TradeRule;
import com.bohai.subAccount.vo.UserContractTradeRule;

public interface TradeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insert(TradeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insertSelective(TradeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    TradeRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKeySelective(TradeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_TRADE_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKey(TradeRule record);
    
    /**
     * 根据客户编号查询交易规则
     * @param userNo
     * @return
     */
    List<UserContractTradeRule> selectTradeRulesByUserNo(String userNo);
    
    /**
     * 根据组ID查询交易规则
     * @param groupId
     * @return
     */
    List<UserContractTradeRule> selectTradeRulesByGroupId(String groupId);
    
    @Delete("delete from T_TRADE_RULE t where exists (select 1 from t_user_contract t1 where t1.user_no = #{0} and t1.contract_no = t.contract)")
    int deleteByUserNo(String userNo);
    
    /**
     * 查询交易规则
     * @param groupId
     * @return
     */
    List<TradeRule> selectTradeRulesByAll();
}