package com.bohai.subAccount.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;

import com.bohai.subAccount.entity.InputOrder;
import com.bohai.subAccount.entity.UserFrozenaccount;

public interface UserFrozenaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_FROZENACCOUNT
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    int insert(UserFrozenaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_FROZENACCOUNT
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    int insertSelective(UserFrozenaccount record);
    
    List<UserFrozenaccount> getUserByUserName(String userName);
    
    int update(UserFrozenaccount record);
    
    int delete(String userName);
    
    UserFrozenaccount getUserByUnfrozen(Map<String,Object> map);
    
    int updateCancelUnfrozen(Map<String,Object> map);
    
    int updateTradeUnfrozen(Map<String,Object> map);
    
    int updatePartUnfrozen(Map<String,Object> map);
    
    int updateTradePartUnfrozen(Map<String,Object> map);
    
    @Delete("delete from T_USER_FROZENACCOUNT")
    int deleteAll();
    
}