package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.Useravailableindb;

public interface UseravailableindbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USERAVAILABLEINDB
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    int insert(Useravailableindb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USERAVAILABLEINDB
     *
     * @mbggenerated Sat May 06 15:46:40 CST 2017
     */
    int insertSelective(Useravailableindb record);
}