package com.bohai.subAccount.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Select;
import org.springframework.test.context.jdbc.Sql;

import com.bohai.subAccount.entity.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    UserInfo selectByPrimaryKey(String id);
    
    
    List<UserInfo> selectByGroupId(String groupId);
    
    List<UserInfo> selectByGroup();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKey(UserInfo record);
    
    @Select("select count(1) from t_user_info where user_name = #{0} and user_pwd = #{1}")
    int countUserInfoByUserNameAndPasswd(String userName, String password);
    
    @Select("select count(1) from t_user_info where group_id = #{0}")
    int countByGroupId(String groupId);
    
    @Select("select CAPITAL from t_user_info where user_name = #{0} ")
    String getUserInfoByUserName(String userName);
    
    List<Map<String, Object>> selectUserInfoByGroupId(UserInfo userInfo);
    
    /**
     * 查询所有用户拥有的合约数量
     * @return
     */
    @Select("select t.USER_NAME  ,t.USER_NO ,count(t1.contract_no) as COUNT from t_user_info t left join t_user_contract t1 on t.USER_NO = t1.USER_NO group by t.USER_NAME,t.USER_NO")
    List<Map<String, Object>> selectUserInstrumentCount();
    
    @Select("select t.USER_NAME,t.USER_NO,count(t1.contract_no) as COUNT from t_user_info t left join T_CLOSE_RULE t1 on t.USER_NAME = t1.USER_NAME group by t.USER_NAME,t.USER_NO")
    List<Map<String, Object>> selectUserRiskCount();
}