package com.bohai.subAccount.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.bohai.subAccount.entity.CapitalRateDetail;

public interface CapitalRateDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int insert(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int insertSelective(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    CapitalRateDetail selectByPrimaryKey(String userName);
    
    @Select(" select  sum(USER_CAPITAL) + sum(HOST_CAPITAL)  as inoutmoney  from T_CAPITAL_RATE_DETAIL where to_date(INSERT_TIME,'yyyymmdd hh24miss')  > to_date('20180109 200101','yyyymmdd hh24miss') "
        + " and to_date(INSERT_TIME,'yyyymmdd hh24miss') < to_date('20180109 200101','yyyymmdd hh24miss') + 1 group by USER_NAME ")

    BigDecimal selectByPrimaryKeyOneday(String userName,String startTime,String endTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int updateByPrimaryKeySelective(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int updateByPrimaryKey(CapitalRateDetail record);
    
    List<CapitalRateDetail> getUserByUserName(String userName);
}