package com.bohai.subAccount.dao;

import com.bohai.subAccount.entity.CapitalRate;

public interface CapitalRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    int insert(CapitalRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    int insertSelective(CapitalRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    CapitalRate selectByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    int updateByPrimaryKeySelective(CapitalRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE
     *
     * @mbggenerated Sun Jul 02 15:50:13 CST 2017
     */
    int updateByPrimaryKey(CapitalRate record);
}