package com.bohai.subAccount.dao;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;

import com.bohai.subAccount.entity.CapitalRateDetail;
import com.bohai.subAccount.entity.CapitalRateDetail2;

public interface CapitalRateDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int insert(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int insertSelective(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    CapitalRateDetail selectByPrimaryKey(String userName);

    CapitalRateDetail2 selectByPrimaryKeyOneday(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int updateByPrimaryKeySelective(CapitalRateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CAPITAL_RATE_DETAIL
     *
     * @mbggenerated Sun Jun 11 19:00:26 CST 2017
     */
    int updateByPrimaryKey(CapitalRateDetail record);
    
    List<CapitalRateDetail> getUserByUserName(String userName);
    
    @Insert("insert into T_CAPITAL_RATE_DETAIL_BAK select t.*,to_char(sysdate,'yyyymmdd hh24:mi:ss') from T_CAPITAL_RATE_DETAIL t ")
    int backup();
    
    @Delete("delete from T_CAPITAL_RATE_DETAIL")
    int deleteall();
}