package com.bohai.subAccount.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.bohai.subAccount.entity.GroupRule;

public interface GroupRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insert(GroupRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insertSelective(GroupRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    GroupRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKeySelective(GroupRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GROUP_RULE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKey(GroupRule record);
    
    List<GroupRule> selectAll();
    
    @Select("select count(1) from T_GROUP_RULE")
    int countAll();
}