package com.bohai.subAccount.dao;

import org.apache.ibatis.annotations.Insert;

import com.bohai.subAccount.entity.InvestorPositionHistory;

public interface InvestorPositionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INVESTOR_POSITION_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insert(InvestorPositionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_INVESTOR_POSITION_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insertSelective(InvestorPositionHistory record);
    
    @Insert("insert into T_INVESTOR_POSITION_HISTORY select t.*,to_char(sysdate,'yyyymmdd') from T_INVESTOR_POSITION t ")
    int backup();
}