package com.bohai.subAccount.dao;

import org.apache.ibatis.annotations.Insert;

import com.bohai.subAccount.entity.OrderHistory;

public interface OrderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insert(OrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_HISTORY
     *
     * @mbggenerated Wed Feb 22 16:49:33 CST 2017
     */
    int insertSelective(OrderHistory record);
    
    @Insert("insert into t_order_history select t.*,to_char(sysdate,'yyyymmdd') from t_order t")
    int backup();
}