package com.bohai.subAccount.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;

import com.bohai.subAccount.entity.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */

    
   int insertSelective(Order record);
    
    List<Order> getUserByUserName(String userName);
    
    List<Order> getCanelByUserName(String userName);
    
    int update(Order record);
    
    int delete(String userName);
    
    Order getOrderByCondition(Map map);
    
    Order getOrderByCondition2(Map map);
    
    /**
     * 删除所有数据
     * @return 删除条数
     */
    @Delete("delete from t_order")
    int deleteAll();
    
    /**
     * 根据合约号，开仓方向查询用户平仓的挂单
     * @param subuserid
     * @param instrumentID
     * @param direction
     * @return
     */
    List<Order> getUserCloseOrderByInstrumentIDAndDirection(String subuserid, String instrumentID,
			String direction);
    
}