package com.bohai.subAccount.dao;

import java.util.List;

import com.bohai.subAccount.entity.UserLogin;

public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_LOGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_LOGIN
     *
     * @mbggenerated Thu Feb 09 17:23:29 CST 2017
     */
    int insertSelective(UserLogin record);
    
    List<UserLogin> getUserByUserName(String userName);
    
    int update(UserLogin record);
    
    int delete(String userName);
}