package com.bohai.subAccount.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;

import com.bohai.subAccount.entity.UserContract;
import com.bohai.subAccount.exception.FutureException;

public interface UserContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insert(UserContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int insertSelective(UserContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    UserContract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKeySelective(UserContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_CONTRACT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    int updateByPrimaryKey(UserContract record);
    
    //@Select("select count(1) from t_user_contract t where t.contract_no = #{contractNo} and exists (select 1 from t_user_info t1 where t.user_no = t1.user_no and t1.user_name = #{userName})")
    @Select("select count(1) from t_user_contract t where t.contract_no = #{contractNo} and user_no = #{userNo}")
    Integer countByContractNo(UserContract record);
    
    @Select("select count(1) from t_user_contract t where t.contract_no = #{contractNo} and exists (select 1 from t_user_info t1 where t.user_no = t1.user_no and t1.user_name = #{userName})")
    Integer countByContractNoAndUserName(UserContract record);
    
    List<UserContract> queryUserContractByUserName(String userName);
    
    List<UserContract> queryUserContractByAll();
    
    @Delete("delete from t_user_contract where user_no = #{0}")
    int deleteByUserNo(String userNo);
    
    @Select("select CONTRACT_UNIT from t_user_contract where CONTRACT_NO = #{0}")
    Integer getContractUnitByContractNo(String contractNo);
    
    UserContract selectByUserNameAndContract(String userName, String contractNo);
}